version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.8.2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://jxafyidhbrvfoe:477c98276b9a7b7cc70245ad4ef2a3ba8e73b606a9625315f454cf3ab1c5b1ab@ec2-44-195-162-77.compute-1.amazonaws.com:5432/d95h30jjffip31
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://jxafyidhbrvfoe:477c98276b9a7b7cc70245ad4ef2a3ba8e73b606a9625315f454cf3ab1c5b1ab@ec2-44-195-162-77.compute-1.amazonaws.com:5432/d95h30jjffip31
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: "myadminsecretkey"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDDTCCAfWgAwIBAgIJXjc9lA7+f2QsMA0GCSqGSIb3DQEBCwUAMCQxIjAgBgNV\nBAMTGWRldi1iaXRnczc4NS51cy5hdXRoMC5jb20wHhcNMjIwNDA0MTEzMjIxWhcN\nMzUxMjEyMTEzMjIxWjAkMSIwIAYDVQQDExlkZXYtYml0Z3M3ODUudXMuYXV0aDAu\nY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6ljfMGd0yBJtIlyq\n2pxgTjAY4huljvNMi/EQVrgXi+D/0ZAcKFI3bJ7DS4XckdxYoqU8gbz7d0ttgGEk\nR/FRsKz61E1ZG0cyl7ZKgMxpWn/gQApC7DtMaFZUBH/5jniHkmgpOv813rNMM3mk\nZdWGh6Nhy/6EOt38eAmG5R0G/fXs/PD5B3/AEtcLz3ztVyFw9w6Yw7iV/f4+bsBM\nVP2pMXqL8dXFrsIT3CdWY5tFfKk0zqpkXZkKkFNhXvtpMDkZpvMB19/znRnb4GK+\neFr3nEnF9S91ela7rul3wPokyxe9xO3jjwa9Uq6ABiIe/jQUyznugLM5W4SPXu10\nMSD3NwIDAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTwvWZOZDq+\nKp5vpT0lGb1fYWZXIDAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEB\nAGO3Sc7kZj7bWblNSV7maeh0nVr/IsJuHyzD1Wt+DekAvh2X28gVc9gS/bdSjCbC\nmFsDoB+NKkP8saYug1LCcHcuYh3iSaCjynwbC4bvlv0SqEBL5pePE0Yzvxhf4g49\nFDIpogcQUcuRTS6mVrJjptk4906hEXBylpmKs5P2VyMuvbYaSCTmgfB4OZKJnaNh\nTAXOfHLSoP2J5PpLDRNwxmvqQOt2y8JOY2c6JuZmzPjxEUX89yOJh1MfSsSeAycl\naAm0Y4T8vcBNB/9G35FyDiv7LE+sC2225W9/ejz7tHOiq/NBn6LQfrgqvqpClW00\nFxGVANbT/TEgxxFq/dc5D9s=\n-----END CERTIFICATE-----"}'
      ACTION_BASE_URL: http://host.docker.internal:3000
volumes:
  db_data:

